### ISSUE TITLE
从git拉取代码编译不通过，报错2017，无法指定/main

### ISSUE THREAD

**Issue by madeinchinalmc** [jijiechen/dotnetclub#13]
**问题：**从github down代码后，执行./build --target=build-all命令报错，如果生成模块或库，则无法指定/main [your prj path/Discussion.Web.csproj ]

**解决方案：**编辑Discussion.Web项目，在<PackageId>Discussion.Web</PackageId>这一行下添加配置
    <RazorCompileToolset>PrecompilationTool</RazorCompileToolset>
**原因**：新的razorsdk的问题，问题详情 -->https://github.com/aspnet/websdk/issues/350

**Comment by jijiechen** [comment]
现在通过相关的 Commit，应该已经修复了这个问题（这个问题是由于添加 `StartupProject` 配置而导致）
