### ISSUE TITLE
开发过程中，修改代码后再次编译前，需要手工结束dotnet.exe进程。

### ISSUE THREAD

**Issue by AndyPlus** [jijiechen/dotnetclub#14]
问题描述：
1.  首次执行`./build --target=ci` （编译成功后可在5010端口访问，但并未生成publish目录）
1.  如果再次执行`./build --target=ci`，提示端口占用，执行此命令后解决`taskkill /im dotnet.exe /f`
1.  如果在Visual Studio中按F5，提示文件被dotnet进程占用，结束进程后按F5，可以在5000端口访问。

需求描述：
* 作为开发者，我需要准确的Readme.md和简洁的开发流程，以便于能够快速的搭建环境参与开发。

**Comment by jijiechen** [comment]
多谢建议，昨晚在线给一些朋友讲了一下怎么开发的问题，接下来，我会继续加强相关资料的整理。

`./build.ps1 -target=ci` 应该只是一个运行编译和单元测试的过程，所以：
1. 会在 `src/Discussion.Web` 下生成 `publish` 目录
1. 5010 端口被占用是因为，自动化测试中有一个“启动测试”，会尝试把应用程序启动起来。问题是，似乎第一次运行、启动进程后，没能成功关闭这个进程（我已经发现这个问题，并且采用了一些方法解决，比如尝试 Kill 目标进程，以及在代码里检测被占用的端口，并尝试其他端口。后面还需要多花一些时间来研究这个问题）
1. 运行 `./buid.ps1 -target=ci` 之后，如果没能成功地结束进程，确实会造成进程被占用的情况。需要手动结束它们，可以使用你提供的命令行，或者在**任务管理器**中找到所有 `dotnet.exe` 并结束掉。


关于开发流程，我尽快整理一个完整一些的文档吧，多谢提醒。

**Comment by jijiechen** [comment]
理论上，现在端口占用和文件占用的情况现在应该是所有好转的。
你可以再试试吗？
