### ISSUE TITLE
Admin的帐号体系跟Web用户的帐号体系是否共用？

### ISSUE THREAD

**Issue by ElderJames** [jijiechen/dotnetclub#15]
Admin的帐号体系跟Web用户的帐号体系是否共用？

**Comment by jijiechen** [comment]
我的计划是不共用，可以在一个数据库，但应该是不同的业务实体，比如 `AdminUser`。
从代码设计上来看，设计一个 Role 系统也能满足需求，但毕竟 Admin 与 Web 的用户是不会重合的。
你说呢？

**Comment by ElderJames** [comment]
我也认为是分开，后期发展两边的权限都是不同的
