### ISSUE TITLE
用户可以使用忘记密码功能重置其登录密码

### ISSUE THREAD

**Issue by jijiechen** [jijiechen/dotnetclub#27]
用户可能在长时间不使用网站后，再次登录时忘记密码。因此，网站希望使用用户已经验证过的邮箱，帮助他们验证对账号的所有权，并自动完成修改密码的步骤。

### 功能一：忘记密码
**如果**用户忘记了登录密码
**当**用户来到登录界面上，他点击“忘记密码”
**那么**，他应该看到一个输入用户名或邮箱的界面
**并且**，他可以使用往账号里已验证的邮箱里发送一封验证邮件

注：

1. 无论用户输入的是用户名还是邮箱，在点击发送邮件后，提示语里不应该包含用户已绑定的邮箱地址；
2. 如果用户之前没有已验证的邮箱，应该给用户提示“无法验证你对账号的所有权，因为之前没有已验证过的邮箱地址”

### 功能二：重新发送邮件
**如果**用户已经使用“忘记密码”功能往已验证的邮箱发送了验证邮件
**当**他发现并没有收到邮件的时候
**那么**他能够使用网页上出现的“再次发送”的链接再次发送验证邮件

注：

为防止发送过多的邮件，应该在页面上倒数 30 秒后，再向用户展示“再次发送”链接。具体实现方式，可参考“个人中心”的验证邮件地址的功能。

### 功能三：修改登录密码
**如果**用户已经在自己的邮箱里，收到了账号验证邮件
**当**他点击邮件中的重置密码的链接
**那么**他应该来到 dotnet club 网站上，并且使用修改密码的界面，完成对登录密码的修改

注：

1. 邮件的有效期为 7 天；无论是链接已过有效期，还是无法被验证，都应该拒绝用户修改密码
2. 邮件里应该标明提示：“如果你没有申请重置密码，请忽略邮件；如果担心账号安全问题，请与 dotnet club 网站联系”；同时，在邮件里还将写明“用户名”信息
3. 用户跟随链接回到网站后的界面，不再要求用户登录，也不再要求他提供现有密码，就可以直接完成对密码的修改

**Comment by wallevy** [comment]
#35
