### ISSUE TITLE
增加隐私协议、GDPR页面

### ISSUE THREAD

**Issue by EdiWang** [jijiechen/dotnetclub#31]
让用户注册、手机邮箱、手机号等数据的网站，最好在页脚加上“隐私协议”页面，并启用GDPR Cookie的询问。

参见：https://docs.microsoft.com/en-us/aspnet/core/security/gdpr?view=aspnetcore-2.2

**Comment by jijiechen** [comment]
隐私协议是要加的，毕竟中国法律有要求。
不过 GDPR 嘛，欧盟的要求我们没必要太 Care 吧，毕竟社区是针对中文区域的。最多加一个声明：不为欧洲人士服务，但鉴于网站的能力限制，我们无法识别用户是否为欧洲人士。
