### ISSUE TITLE
dapper + mysql 会不会更好？

### ISSUE THREAD

**Issue by zhaopeiym** [jijiechen/dotnetclub#4]

**Comment by jijiechen** [comment]
多谢提议。
Dapper 是非常不错的数据库中间件，小而美；MySQL 也是不错的开源数据库，可能后续会选用。
目前，项目还在持续开发中，之后可能会换用更好的数据库。暂时主要是先专注于要把功能完成，用  EF Core 开发也是不错的选择，另外文件数据库能够让开发期间更方便。

**Comment by jijiechen** [comment]
现在，dotnet club 已经支持 PostgreSQL 数据库。
并且，线上的 dotnet club 网站也迁移到了 [PostgreSQL 数据库](https://dotnetclub.net/topics/64)。
