### ISSUE TITLE
开论坛 备案不需要资质吗？

### ISSUE THREAD

**Issue by zhaopeiym** [jijiechen/dotnetclub#5]

**Comment by jijiechen** [comment]
需要的，目前域名正在备案中，期待能通过。
目前，在预览版本测试期间，服务器在境外。

**Comment by jijiechen** [comment]
根据中国国务院 2014 年 9 月 29 公布的废止“电子公告”类信息服务需要专项审批的决定，以及阿里云刊载的相关解读，现在应该开论坛是不再需要单独的特别审批了。

参考资料：

* http://www.miit.gov.cn/n1146295/n1146557/n1146624/c3554796/content.html
* http://www.miit.gov.cn/n1146295/n1652858/n1653018/c3780584/content.html
* https://www.aliyun.com/zixun/content/2_6_486682.html
