### ISSUE TITLE
线上的网站，以 HTTPS 访问时，生成图片链接仍产生为非 HTTPS 链接

### ISSUE THREAD

**Issue by jijiechen** [jijiechen/dotnetclub#56]
实例参见：
https://dotnetclub.net/topics/63

这导致页面被浏览器标记不“部分内容不安全”。

**Comment by ElderJames** [comment]
就是上传时生成链接的问题

**Comment by jijiechen** [comment]
此问题已于下面的 Commit 修复：https://github.com/jijiechen/dotnetclub/commit/1cb0998ffbdb4ef92d79ce502fa7e1704e8122f5
