### ISSUE TITLE
建议：把一些零碎简单的任务放到issue中，标注为help wanted

### ISSUE THREAD

**Issue by zwcloud** [jijiechen/dotnetclub#6]
把一些零碎简单的任务放到issue中，加上label：help wanted，然后加上一点说明，比如应该怎么入手解决，有什么大体思路，有什么可以参考的资料等等。

其他人（比如我）就可以帮忙入手做这些事情了。

**Comment by jijiechen** [comment]
这是个好主意，我接下来会尝试去组织。
暂时请查看 [Projects](https://github.com/jijiechen/dotnetclub/projects) 页面了解最近的开发计划。

**Comment by jijiechen** [comment]
@zwcloud 我已经在着手这件事了，请留意哦
目前添加了“用户中心”功能。
