### ISSUE TITLE
请问是不是打算把管理后台也放到web项目里面？

### ISSUE THREAD

**Issue by ElderJames** [jijiechen/dotnetclub#7]
我看了下代码，把数据操作也写在一个Web项目里了。那么管理后台如果是用Angular，调用的也是Web里的Api吧？
如果是这样，我可以提交一个集成ng-alain的pr，会跟我的这个实例项目一样：https://github.com/ElderJames/aspnetcore-ng-alain

我也正在做一个项目，https://github.com/ElderJames/wizard-cinema ，已经在用这个组件库了。是使用jwt做验证授权的。

**Comment by jijiechen** [comment]
我是计划将管理后台放一个独立的项目的，计划做一个 SPA 应用。
它的用户系统完全独立，包括认证也是独立的（可以使用 JWT），因此可以独立部署。

至于数据访问的方面，你可以发现它只有一个 `IRepository` 并没有什么特别的东西。如果想复用，主要需要考虑的是 Model 的复用。

**Comment by ElderJames** [comment]
你意思是另外创建一个webapi项目，提供接口给spa应用？那么至少数据访问（IRepository、Model和DbContext）也要独立出来给这两个项目公用

**Comment by jijiechen** [comment]
是这样的。
因此，可以建一个 `Discussion.Core` 项目，供两者公用。然后，可以创建 `Discussion.Admin` Web 项目。

你认为如何？
